### ISSUE TITLE
Helloword安装依赖报错求指教

### ISSUE THREAD

**Issue by RockZhou8** [SuperManito/LinuxMirrors#7]
##. 详细叙述您的问题
### (1) 具体问题
樱花大佬，实在是没辙了，只能在这里写issue，这个问题困扰我3个月了，Helloworld容器内，npm install xxx任何依赖，都报同样的错误。
已经是最新镜像了。
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
sup....oworld   latest    0640a4fe8541   5 days ago     178MB

### (2) 详细的系统日志

 npm install -g formdate
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)

**Comment by SuperManito** [comment]
npm install -g form-data

**Comment by RockZhou8** [comment]
> npm install -g form-data
那个formdata是笔误，实际上npm install -g XXX任何一个依赖都报错,直接"npm"也报错。
```
root@jd:/jd $ npm install -g form-data
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

**Comment by SuperManito** [comment]
taskctl env repairs

**Comment by RockZhou8** [comment]
> ```
> taskctl env repairs && taskctl env install
> ```

报issue前试过了，刚又试了下，自然还是报了同样的错误...
在出了9月正式版之前的版本也同样如此。
现在正式版之后每次更新都是手动 rm /opt 和 删除容器之后，手动拉最新版docker镜像通过docker-compose 部署的，yml文件也是dockerhub主页上面最新那个，一字未改。

**Comment by SuperManito** [comment]
有这么神奇？

1. 什么架构
    uname -m
2. 不全局安装进入目录后安装能不能装上
    cd <path> && npm install xxx

或者TG私聊我 Todesk远程给你看看
